### ISSUE TITLE
Cortana Support

### ISSUE THREAD

**Issue by longhai18** [DominicMaas/SoundByte#4]
It would be great if I can play song or any playlist with Cortana.

**Comment by DominicMaas** [comment]
Support has been added for playing a users SoundCloud stream and likes via Cortana. I will write up a doc where people can decide what else should be added and how the voice command should work.

**Comment by DominicMaas** [comment]
The protocol system has been overhauled to allow easy addition of new Cortana Commands. The ability to play SoundByte/SoundCloud/Fanburst/YouTube likes was also added.

I'll close this issue, but any additional Cortana commands can be requested through [here](https://github.com/DominicMaas/SoundByte/issues/17).
