### ISSUE TITLE
playing stuff but no time, oh wait it cheashed

### ISSUE THREAD

**Issue by Mom-Assistance** [DominicMaas/SoundByte#5]
this ![image](https://cdn.discordapp.com/attachments/340376379155808257/340738931324616705/unknown.png)
then this ![image](https://cdn.discordapp.com/attachments/340376379155808257/340744607216435200/unknown.png)
then a crash
I am making a copy of this but this one I'm running is from the windows store.

**Comment by Mom-Assistance** [comment]
![image](https://user-images.githubusercontent.com/24907538/28742842-02f81e50-73f8-11e7-82fb-a2f2534b1fce.png)
this just happend too

**Comment by Mom-Assistance** [comment]
sems to be caused my changing tracks

**Comment by DominicMaas** [comment]
Let me know if you encounter the same issue when running the latest commits from GitHub. I'll check the crash logs.

**Comment by Mom-Assistance** [comment]
i made a dump file, and i can get it to run in visual studio but ok

**Comment by Mom-Assistance** [comment]
i changed the startup project to "Soundbyte.UWP" and gives 
![image](https://user-images.githubusercontent.com/24907538/28747938-17998a22-7468-11e7-87a1-2cc0b8a69c0f.png) (new and old cmments) 
I checked the location and no dll is there

**Comment by DominicMaas** [comment]
The DLL Should be automatically generated when building the project. Try building SoundByte.Core manually. Also make sure you open SoundByte.sln in the root project.

**Comment by Mom-Assistance** [comment]
yes it did
and i got it to build with new commints 
![image](https://user-images.githubusercontent.com/24907538/28748191-8b5a1750-746e-11e7-8a8a-1eabbc1e2ae0.png) 
but im still getting the crashing problem...
it looks like this 
![image](https://user-images.githubusercontent.com/24907538/28748206-b8607d7a-746e-11e7-8ed7-c9db61795637.png)
and i cant click anything  
the skip track pause and back track buttons on my keyboard stops working 
sound still plays

**Comment by Mom-Assistance** [comment]
![image](https://user-images.githubusercontent.com/24907538/28748227-4f9fd96a-746f-11e7-82fb-eaf5a9f084e0.png)

**Comment by DominicMaas** [comment]
Two Questions,

Is there a loading bar up the top when this happens?

And does the app freeze when clicking another item (plays the first time, but when switching to a new song, it freezes)?

**Comment by Mom-Assistance** [comment]
no loading bar and it freezes is i skip a track by click or with keyboard buttens

**Comment by DominicMaas** [comment]
Everytime?

What are your PC specs?

**Comment by Mom-Assistance** [comment]
the one I'm running it on Windows 10 Pro preview build 16241 4gb ram 2.5ghz processor 1tb hdd
the app never uses more than 88mb of ram

**Comment by DominicMaas** [comment]
Ahhh you're using a preview build. That might be causing the issue. Another issue could be internet speeds, what are your internet speeds like?

**Comment by Mom-Assistance** [comment]
im useing my phons data i dont know

**Comment by Mom-Assistance** [comment]
but it fast

**Comment by DominicMaas** [comment]
Could you run a speed test, e.g http://www.speedtest.net/

**Comment by Mom-Assistance** [comment]
the one u sent me didn't work so i took the google one 
![image](https://user-images.githubusercontent.com/24907538/28748339-8e99841a-7472-11e7-89ec-db35eea78d3a.png)

**Comment by Mom-Assistance** [comment]
i clicked this and it stopped working again 
![image](https://user-images.githubusercontent.com/24907538/28748344-b6764676-7472-11e7-9405-d3b169ba06a5.png)

**Comment by DominicMaas** [comment]
I'll try take a look into everything, I have a feeling that it is caused by the preview build of Windows 10.

**Comment by Mom-Assistance** [comment]
im looking thru the player in the code

**Comment by Mom-Assistance** [comment]
and the playlist

**Comment by Mom-Assistance** [comment]
Windows is activated
it has to be something with the interface or loading the tracks bc i cant click anything
i changed a few things and how it looks compleetly and still hapens

**Comment by DominicMaas** [comment]
It has nothing to do with Windows being activated or not, or the app (to a point). There is a bug in the Preview versions of Windows 10 that breaks the app. You will have to wait untill the next insider build.

**Comment by Mom-Assistance** [comment]
ok thank you
