### ISSUE TITLE
your README violates MIT

### ISSUE THREAD

**Issue by Venomed** [DominicMaas/SoundByte#7]
Given your repo not only is tagged as MIT (which could have been a system error) you're also using standard MIT blob file and then your README is explicitly forbidding distribution which is against the terms of License, you can no longer use MIT as it is and shouldn't label the content as MIT licensed.

This is just my understanding as a developer and not a legal advice but I feel you should either remove restriction on license or update the LICENSE blob to a compatible state.

In any case, thanks for sharing your work on github. Not what I was looking for but I'll explore it as a UWP project implementation to learn from and for that I'm grateful. 😄 👍

**Comment by DominicMaas** [comment]
Thanks for letting me know, I had forgotten to remove the MIT license from my project.
