### ISSUE TITLE
Now Playing Indicator + Keyboard Shortcuts

### ISSUE THREAD

**Issue by DamSenViet** [DominicMaas/SoundByte#8]
I was wondering if there would ever be support for a playing glyph on top of the current playing song. After choosing to play a song, there's no visual indicator that its actual playing (except for bottom now playing). You might not know how far you are into a playlist for example just by looking. You'd have to go to the queue just to check which is imo p tedious.

Also I was wondering whether you'd implement a keyboard shortcut to go back. I find it a little cumbersome to move my mouse over to the top left just to go from now playing to the normal menu.

**Comment by DominicMaas** [comment]
1) That is a great idea, I've made some improvements to the app recently meaning that I should be able to implement that idea very quickly (next hour).

2) What key do you think would be best for going back, what key do you normally use in other apps? (Backspace?)

**Comment by DamSenViet** [comment]
I normally use alt-backspace (chrome's previous page shortcut). It seems the most intuitive to me. Chrome's previous page button is always in top left. It makes sense to have the back button do the same thing with the same trigger.

**Comment by DominicMaas** [comment]
I have implemented a playing glyph to let the user know which song is playing and have implemented alt+backpace to go back. These changes will be in the GitHub soon and published to the Windows Store in a few hours. Thanks!
