### ISSUE TITLE
Search Input Box Needs More Margin

### ISSUE THREAD

**Issue by DamSenViet** [DominicMaas/SoundByte#9]
Now I'm just nitpicking, but the search input box begins slightly too close to the icon's right border:

![image](https://user-images.githubusercontent.com/26016342/31786972-1a878b34-b4bf-11e7-9bc9-0f80dfbe6f9c.png)

You can see how the input begins at the very edge (almost on top of the border).

I was thinking maybe you could reduce the icons right padding and add more margin in between the icons and the text/input.

**Comment by DominicMaas** [comment]
This has been fixed (due to using a new hamburger control in the Fall Creators Update).

![screenshot 404](https://user-images.githubusercontent.com/5589453/32043685-fbcd2fbc-ba97-11e7-9ad9-1886ecc564a1.png)
